# Generated by Django 3.2.9 on 2021-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desired_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
