# Generated by Django 3.2.9 on 2021-12-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cost',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.CharField(max_length=20),
        ),
    ]
