# Generated by Django 3.2.9 on 2021-12-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211210_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
