# Generated by Django 3.2.9 on 2021-12-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
