# Generated by Django 3.2.9 on 2021-12-02 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211202_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collected_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 14, 16, 48, 907039)),
        ),
    ]
