# Generated by Django 3.2.9 on 2022-01-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_usersaccount_location'),
        ('products', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('UnAvailable', 'UnAvailable')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.district'),
        ),
        migrations.AlterField(
            model_name='product',
            name='house_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='road_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
