# Generated by Django 3.2.9 on 2022-01-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220102_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_category',
            field=models.CharField(choices=[('Published', 'Published'), ('Waste', 'Waste')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
