# Generated by Django 3.2.9 on 2021-12-02 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_collected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collected_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 14, 17, 51, 446145, tzinfo=utc)),
        ),
    ]
