# Generated by Django 3.2.9 on 2021-12-02 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_collected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collected_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
