# Generated by Django 3.2.9 on 2021-12-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='is_manufacture',
            field=models.BooleanField(default=False),
        ),
    ]
