# Generated by Django 3.2.9 on 2022-01-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_usersaccount_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaccount',
            name='location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userauth.district'),
        ),
    ]
